# Generated by Django 6.0.3 on 2026-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('package', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_txn_id', models.CharField(max_length=100, unique=True)),
                ('txn_ref', models.CharField(blank=True, max_length=100)),
                ('bank_code', models.CharField(blank=True, max_length=50)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='initiated', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('payment_date', models.CharField(blank=True, max_length=100)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
