# Generated by Django 6.0.3 on 2026-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbyark_app', '0002_destination_tourpackage_delete_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='highlights',
            field=models.TextField(blank=True, help_text='Enter each feature on a new line. These show as bullet points.', null=True),
        ),
    ]
