# Generated by Django 6.0.3 on 2026-06-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbyark_app', '0003_destination_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='highlights',
        ),
    ]
