# Generated by Django 6.0.3 on 2026-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbyark_app', '0005_bookingenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', help_text='Select destination type', max_length=20),
        ),
    ]
